import { Record, Map, OrderedMap } from 'immutable';

export const ApiRecord = new Record({
	state:0,
	success:false,
	error:false
});
export const Filters = new Record({
	patient:0,
	day:0,
	room_id:0
});


export const stateRecord = new Record({
	loaded:false,
	errors:[],
	user_id:0,
	api:Map({}),
	rooms:Map({}),
	users:Map({}),
	blog:OrderedMap({}),
	oldBlog:Map({}),
	loaded:false,
	visits:OrderedMap({}),
	filters:new Filters({}),
	config:Map({}),
	holidays:Map({}),
});

export const Blog = new Record({
  id:0,
  body:'',
  link:'',
  created_at:'',
  expire_at:'',
  user_id:0,
});

export const holiday = new Record({
  id:0,
  room_id:0,
  day:'',
  starting_hour:'',
  ending_hour:'',
  size:'',
  user_id:0,
});

export const Icsi = new Record({
  id:0,
  patient:'',
  patient_age:'',
  is_pregnant:'',
  services:'',
  husband:'',
  husband_age:'',
  phone:'',
  note:'',
  hcg:'',
  e2:'',
  hepatitis:'',
  indications:'',
  history:'',
  prev_art:'',
  protocol:'',
  stdays:'',
  final_e2:'',
  final_p4:'',
  day_of_et:'',
  hmg_tradename:'',
  hmg_num:'',
  fsh_tradename:'',
  fsh_num:'',
  recfsh_tradename:'',
  recfsh_num:'',
  hcg_tradename:'',
  hcg_num:'',
  andro_embryologist:'',
  andro_prep:'',
  pre_vol:'',
  pre_conc:'',
  pre_mot:'',
  pre_rp:'',
  pre_abn:'',
  post_vol:'',
  post_conc:'',
  post_mot:'',
  post_rp:'',
  post_abn:'',
  oocyte_or:'',
  oocyte_intact:'',
  oocyte_m2:'',
  oocyte_m1:'',
  oocyte_gv:'',
  oocyte_injected:'',
  oocyte_fert_rate:'',
  embryo_d1:'',
  embryo_d2:'',
  embryo_d3:'',
  embryo_d3_a:'',
  embryo_d5:'',
  embryo_et:'',
  embryo_vit:'',
  embryo_blast_rate:'',
  lah_indications:'',
  lah_no:'',
  lah_grade:'',
  injection_time:'',
  incubator_media:'',
  incubator:'',
  incubator_notes:'',
  transfer_day:'',
  transfer_no:'',
  transfer_catheter:'',
  transfer_e_d:'',
  transfer_clinician:'',
  transfer_embryologist:'',
  transfer_witness:'',
  transfer_notes:'',
  last_update:'',
  card_id:0,
  status:'',
  serial_no:'',
  created_at:'',
  created_by:'',
  last_access:'',
});
export const Invitation = new Record({
  id:0,
  name:'',
  used:'',
});
export const Push = new Record({
  uid:0,
  token:'',
});
export const Room = new Record({
  id:0,
  name:'',
  starting_hour:8,
  ending_hour:15,
  interval:30,
  weekend:[],
});
export const Token = new Record({
  user_id:0,
  token:'',
  created_at:'',
  last_login:'',
  ip:'',
});
export const User = new Record({
  id:0,
  role:'',
  username:'',
  password:'',
  token:'',
  fullname:'',
  fb_id:0,
  fb_data:'',
  last_login:'',
});
export const Visit = new Record({
  id:0,
  day:'',
  slot:'',
  type:'',
  status:'',
  ref_id:0,
  user_id:0,
  room_id:0,
  services:'',
  patient:'',
  patient_age:'',
  husband:'',
  husband_age:'',
  phone:'',
  note:'',
  e2:'',
});
