export const API_START = "/API/STARTED";
export const API_SUCCESS = "/API/SUCCESS";
export const API_FAILED = "/API/FAILED";
export const API_FINALLY = "/API/FINALLY";
export const API_ACCESS_DENIED = "/API/ACCESS_DENIED";
export const APP_START = "/APP/START";

export const LOGIN = "IVF/USER/LOGIN/";
export const LOGOUT = "IVF/USER/LOGOUT/";

export const GETAPPCONFIG = "IVF/GETAPPCONFIG/";

export const GETNEWBLOGS = "IVF/GETNEWBLOGS/";
export const MARKASOLD = "IVF/BLOG/MARKOLD";
export const CREATEABLOGPOST = "IVF/CREATEABLOGPOST/";
export const DELETEABLOGPOST = "IVF/DELETEABLOGPOST/";

export const GETVISITS = "IVF/GETVISITS/";
export const SETVISITFILTER = "IVF/SETVISITFILTER/";
export const GETVISITDETAILS = "IVF/GETVISITDETAILS/";
export const UPDATEVISIT = "IVF/UPDATEVISIT/";
export const DELETEVISIT = "IVF/DELETEVISIT/";

export const CREATEINVITATION = "IVF/CREATEINVITATION/";
export const GETINVITATIONS = "IVF/GETINVITATIONS/";

export const SENDAFEEDBACK = "IVF/SENDAFEEDBACK/";
export const GETFEEDBACKS = "IVF/GETMYFEEDBACKS/";
export const GETFEEDBACK = "IVF/GETFEEDBACK/";
export const REPLYTOAFEEDBACK = "IVF/REPLYTOAFEEDBACK/";
export const MARKFEEDBACKASIMPORTANT = "IVF/MARKFEEDBACKASIMPORTANT/";
